name: gymnasium-recorder
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy
  - pillow
  - python-dotenv
  - pygame
  - pip
  - pip:
      - vizdoom
      - ale-py
      - gymnasium[atari]
      - gymnasium[vizdoom]
      - datasets
      - opencv-python
